options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'

steps:
  - name: node:18.12.1
    entrypoint: npm
    args: ['install']

  - name: node:18.12.1
    entrypoint: npm
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - function-1
      - --region=europe-west1
      - --source=dist
      - --trigger-http
      - --runtime=nodejs18
